// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7XD6rZKPCj7zRCEkD3OSz_AuiRfEBSA8',
    appId: '1:52012778547:web:3b7f463f69a1be79310f46',
    messagingSenderId: '52012778547',
    projectId: 'lich-571a3',
    authDomain: 'lich-571a3.firebaseapp.com',
    databaseURL: 'https://lich-571a3-default-rtdb.firebaseio.com',
    storageBucket: 'lich-571a3.firebasestorage.app',
    measurementId: 'G-J4R334K9HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf12OqgTt2gzwpIkrkr76nD-u0s9l9g78',
    appId: '1:52012778547:android:2a9b5905610f6e2f310f46',
    messagingSenderId: '52012778547',
    projectId: 'lich-571a3',
    databaseURL: 'https://lich-571a3-default-rtdb.firebaseio.com',
    storageBucket: 'lich-571a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2XJXLfwz3b-WBhymxwArfjGT1EsAO7o',
    appId: '1:52012778547:ios:56de80d5b3b434ad310f46',
    messagingSenderId: '52012778547',
    projectId: 'lich-571a3',
    databaseURL: 'https://lich-571a3-default-rtdb.firebaseio.com',
    storageBucket: 'lich-571a3.firebasestorage.app',
    iosBundleId: 'com.example.mypham1m5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2XJXLfwz3b-WBhymxwArfjGT1EsAO7o',
    appId: '1:52012778547:ios:56de80d5b3b434ad310f46',
    messagingSenderId: '52012778547',
    projectId: 'lich-571a3',
    databaseURL: 'https://lich-571a3-default-rtdb.firebaseio.com',
    storageBucket: 'lich-571a3.firebasestorage.app',
    iosBundleId: 'com.example.mypham1m5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7XD6rZKPCj7zRCEkD3OSz_AuiRfEBSA8',
    appId: '1:52012778547:web:3bbdcb2a1779b0ba310f46',
    messagingSenderId: '52012778547',
    projectId: 'lich-571a3',
    authDomain: 'lich-571a3.firebaseapp.com',
    databaseURL: 'https://lich-571a3-default-rtdb.firebaseio.com',
    storageBucket: 'lich-571a3.firebasestorage.app',
    measurementId: 'G-HNF1KHFM98',
  );
}
