// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNfWkkrNGLEFVoWDEJK6CU84s1BVLmyg',
    appId: '1:938380451297:web:5939960061f917acbe06a0',
    messagingSenderId: '938380451297',
    projectId: 'spa1m5',
    authDomain: 'spa1m5.firebaseapp.com',
    databaseURL: 'https://spa1m5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spa1m5.firebasestorage.app',
    measurementId: 'G-Z4L1LWZJDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBxtLllbfW90wRMXe97JPpKUDhjjsfKHU',
    appId: '1:938380451297:android:d09045ed8fccd4d9be06a0',
    messagingSenderId: '938380451297',
    projectId: 'spa1m5',
    databaseURL: 'https://spa1m5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spa1m5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtBPQR4KE2Uwh8m7tWfJIl7qOQ5683Y9s',
    appId: '1:938380451297:ios:4b7aa42af47cac75be06a0',
    messagingSenderId: '938380451297',
    projectId: 'spa1m5',
    databaseURL: 'https://spa1m5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spa1m5.firebasestorage.app',
    iosBundleId: 'com.example.mypham1m5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtBPQR4KE2Uwh8m7tWfJIl7qOQ5683Y9s',
    appId: '1:938380451297:ios:4b7aa42af47cac75be06a0',
    messagingSenderId: '938380451297',
    projectId: 'spa1m5',
    databaseURL: 'https://spa1m5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spa1m5.firebasestorage.app',
    iosBundleId: 'com.example.mypham1m5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDNfWkkrNGLEFVoWDEJK6CU84s1BVLmyg',
    appId: '1:938380451297:web:5d6d5a9741879c4fbe06a0',
    messagingSenderId: '938380451297',
    projectId: 'spa1m5',
    authDomain: 'spa1m5.firebaseapp.com',
    databaseURL: 'https://spa1m5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spa1m5.firebasestorage.app',
    measurementId: 'G-7QKZHT8FQ1',
  );
}
